### ISSUE TITLE
Material UI 3 + Typescript giving error with label props 

### ISSUE THREAD

**Issue by monkeymon** [dmtrKovalenko/material-ui-pickers#698]
After upgrading material ui to v3, it start to give the following errors

`
Property 'label' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DatePickerModalProps, any, any>> & Reado...'`

**Comment by snk5000** [comment]
The same problem with placeholder

**Comment by lukas-zech-software** [comment]
Workaround until this library is updated:

```typescript
// mui-date-picker.d.ts
declare module 'material-ui-pickers/DateTimePicker' {

  import { ComponentClass } from 'react';
  import { DateTimePickerModalProps } from 'material-ui-pickers/DateTimePicker/DateTimePickerModal';
  import { InputBaseProps } from '@material-ui/core/InputBase';

  const DateTimePickerModal: ComponentClass<DateTimePickerModalProps & { label: string; InputProps: InputBaseProps }>;

  export default DateTimePickerModal;
}

```

**Comment by dmtrKovalenko** [comment]
Closed
