### ISSUE TITLE
Discrepancy between react dependency and react typings versions

### ISSUE THREAD

**Issue by depsir** [dmtrKovalenko/material-ui-pickers#944]
This is a followup of #939 after I dug deeper into my problem. I'm not sure that this is caused entirely by material-ui-pickers, but it's a starting point to resolve my problem.

Problem: typescript compilation fails even if dependencies are satisfied

Dependencies from minimal example's package json
```
  2   "dependencies": {
  3     "@material-ui/core": "3.9.0",
  4     "@types/react": "16.8.4",
  5     "material-ui-pickers": "2.2.4",
  6     "react": "16.8.4",
  7     "typescript": "^3.3.3333"
  8   },
```

I also added a sample index.tsx file:
```
 import React from 'react';
import { DateTimePicker } from "material-ui-pickers";

React.render(<div />)
```

If I run `npx tsc index.tsx` I get lots of compilation errors saying `Namespace 'React' has no exported member 'PropsWithChildren'`

As a matter of fact, `PropsWithChildren` is introduced in `@types/react@16.8.5` so one simple solution would be to update typings to at least that version. But I want typings and react to be at the very same version, it wouldn't make sense otherwise. But then I will be forced to update to a newer version of react.

So how does this fit with the fact that material-ui-pickers requires at least react 16.3.0 but in reality only compiles with react 16.8.5?

I think I'm missing some pieces, starting from the fact that material-ui-pickers code does not include any `PropsWithChildren`. But where does that come from then?

I hope this issue helps to make a better product for everyone

**Comment by dmtrKovalenko** [comment]
Actually react typings are not synced with react version you are using. Breaking changes not introduced. But important bug fixes applying. So I suggest to just update the typings. :)

**Comment by depsir** [comment]
> Actually react typings are not synced with react version you are using
I was suspecting that but... see considerations below

> So I suggest to just update the typings
But doing so I could end up using new non breaking features that the version of react I'm using does not provide, and the typescript compiler would be ok with that, resulting in a runtime error.
What is the point then of using typescript at all?
